# Standard commodities list found in data.gov.in API
# This helps in fuzzy matching user input to API expected names

COMMODITIES = [
    "Tomato", "Potato", "Onion", "Green Chilli", "Red Chilli", 
    "Brinjal", "Cabbage", "Cauliflower", "Ladies Finger", "Bitter Gourd",
    "Bottle Gourd", "Pumpkin", "Cucumber", "Capsicum", "Drumstick",
    "Beans", "Carrot", "Radish", "Beetroot", "Turnip",
    "Sweet Potato", "Tapioca", "Yam", "Colocasia",
    "Ginger", "Garlic", "Lemon", "Mango", "Banana", "Papaya",
    "Apple", "Orange", "Grapes", "Pomegranate", "Pineapple",
    "Guava", "Water Melon", "Musk Melon", "Custard Apple", "Sapota",
    "Jack Fruit", "Sweet Lime", "Lime", "Pear", "Plum", "Peach",
    "Ridge Gourd", "Snake Gourd", "Cluster Beans", "French Beans",
    "Field Pea", "Cowpea", "Coriander", "Spinach", "Mint", "Methi",
    "Curry Leaves", "Turmeric", "Coriander Seeds", "Cumin", "Tamarind",
    "Rose", "Marigold", "Jasmine", "Tube Rose", "Chrysanthemum",
    "Paddy(Dhan)(Common)", "Rice", "Wheat", "Maize", "Bajra", "Jowar", 
    "Ragi", "Barley", "Arecanut", "Cashewnuts", "Castor Seed",
    "Arhar (Tur/Red Gram)(Whole)", "Gram Raw(Whole)", "Lentil (Masur)(Whole)",
    "Moong(Green Gram)(Whole)", "Urad(Black Gram)(Whole)",
    "Groundnut", "Mustard", "Soyabean", "Sunflower", "Sesamum",
    "Cotton", "Jute", "Coconut", "Sugarcane", "Tobacco"
]

# Common aliases mapping (User input -> API Standard)
CROP_ALIASES = {
    "aloo": "Potato",
    "bhendi": "Ladies Finger",
    "bhindi": "Ladies Finger",
    "pyaaz": "Onion",
    "tamatar": "Tomato",
    "mirchi": "Green Chilli",
    "chilli": "Green Chilli",
    "chili": "Green Chilli",
    "green chili": "Green Chilli",
    "red chili": "Red Chilli",
    "dhan": "Paddy(Dhan)(Common)",
    "paddy": "Paddy(Dhan)(Common)",
    "rice": "Rice",
    "baingan": "Brinjal",
    "eggplant": "Brinjal",
    "gobi": "Cauliflower",
    "patta gobi": "Cabbage",
    "adrak": "Ginger",
    "lahsun": "Garlic",
    "nimbu": "Lemon",
    "kela": "Banana",
    "aam": "Mango",
    "orange": "Orange",
    "santra": "Orange",
    "mosambi": "Sweet Lime",
    "haldi": "Turmeric",
    "dhaniya": "Coriander",
    "jeera": "Cumin",
    "imli": "Tamarind",
    "palak": "Spinach",
    "methi": "Methi",
    "kadi patta": "Curry Leaves",
    "jackfruit": "Jack Fruit",
    "custard apple": "Custard Apple",
    "sapota": "Sapota",
    "chikoo": "Sapota",
    "chiku": "Sapota",
    "kakdi": "Cucumber",
    "kheera": "Cucumber",
    "shimla mirch": "Capsicum",
    "gajar": "Carrot",
    "mooli": "Radish",
    "matar": "Field Pea",
    "lobia": "Cowpea",
    "moong": "Moong(Green Gram)(Whole)",
    "urad": "Urad(Black Gram)(Whole)",
    "tur": "Arhar (Tur/Red Gram)(Whole)",
    "toor": "Arhar (Tur/Red Gram)(Whole)",
    "gram": "Gram Raw(Whole)",
    "chana": "Gram Raw(Whole)"
}
