
TRANSLATIONS = {
    "en": {
        "title": "🌾 AI Farmer Advisory System",
        "settings": "🌐 Settings",
        "lang_select": "Language",
        "farmer_details": "📝 Farmer Details",
        "crop_name": "Crop Name",
        "location": "Village / City",
        "state": "State",
        "quantity": "Quantity (kg)",
        "cost": "Cultivation Cost (₹)",
        "days": "Days since harvest",
        "crop_image": "📸 Crop Image",
        "take_photo": "Take crop photo",
        "analyze": "🚀 Analyze",
        "analyzing": "Analyzing...",
        "error_req": "❌ Crop and Location are required",
        "results": "📊 Analysis Result",
        "price": "Price",
        "freshness": "Freshness",
        "quality": "Quality",
        "profit": "Profit",
        "recommendation": "Recommendation",
        "captured": "Captured",
        "cold_storage": "❄️ Cold Storage Suggestion",
        "cs_msg": "Storing is more profitable! (+{profit_diff}%)",
        "nearest_cs": "Nearest Cold Storage",
        "open_map": "Open Map"
    },
    "hi": {
        "title": "🌾 एआई किसान सलाहकार प्रणाली",
        "settings": "🌐 सेटिंग्स",
        "lang_select": "भाषा",
        "farmer_details": "📝 किसान विवरण",
        "crop_name": "फसल का नाम",
        "location": "गाँव / शहर",
        "state": "राज्य",
        "quantity": "मात्रा (किलो)",
        "cost": "खेती की लागत (₹)",
        "days": "कटाई के बाद के दिन",
        "crop_image": "📸 फसल की फोटो",
        "take_photo": "फोटो लें",
        "analyze": "🚀 विश्लेषण करें",
        "analyzing": "विश्लेषण हो रहा है...",
        "error_req": "❌ फसल और स्थान आवश्यक हैं",
        "results": "📊 विश्लेषण परिणाम",
        "price": "कीमत",
        "freshness": "ताजापन",
        "quality": "गुणवत्ता",
        "profit": "लाभ",
        "recommendation": "अनुशंसा",
        "captured": "दर्ज किया गया",
        "cold_storage": "❄️ शीत भंडार (Cold Storage) सुझाव",
        "cs_msg": "भंडारण करना अधिक लाभदायक है! (+{profit_diff}%)",
        "nearest_cs": "निकटतम शीत भंडार",
        "open_map": "मैप खोलें"
    },
    "te": {
        "title": "🌾 AI రైతు సలహాదారు వ్యవస్థ",
        "settings": "🌐 సెట్టింగులు",
        "lang_select": "భాష",
        "farmer_details": "📝 రైతు వివరాలు",
        "crop_name": "పంట పేరు",
        "location": "గ్రామం / నగరం",
        "state": "రాష్ట్రం",
        "quantity": "పరిమాణం (kg)",
        "cost": "సాగు ఖర్చు (₹)",
        "days": "కోత కోసి ఎన్ని రోజులు అయింది",
        "crop_image": "📸 పంట ఫోటో",
        "take_photo": "ఫోటో తీయండి",
        "analyze": "🚀 విశ్లేషించు",
        "analyzing": "విశ్లేషిస్తోంది...",
        "error_req": "❌ పంట మరియు స్థానం అవసరం",
        "results": "📊 విశ్లేషణ ఫలితం",
        "price": "ధర",
        "freshness": "తాజాదనం",
        "quality": "నాణ్యత",
        "profit": "లాభం",
        "recommendation": "సిఫార్సు",
        "captured": "గ్రహించబడింది",
        "cold_storage": "❄️ కోల్డ్ స్టోరేజీ సూచన",
        "cs_msg": "నిల్వ చేయడం ఎక్కువ లాభదాయకం! (+{profit_diff}%)",
        "nearest_cs": "దగ్గరి కోల్డ్ స్టోరేజీ",
        "open_map": "మ్యాప్ తెరవండి"
    },
     "ta": {
        "title": "🌾 AI விவசாய ஆலோசகர்",
        "settings": "🌐 அமைப்புகள்",
        "lang_select": "மொழி",
        "farmer_details": "📝 விவசாயி விவரங்கள்",
        "crop_name": "பயிர் பெயர்",
        "location": "கிராமம் / நகரம்",
        "state": "மாநிலம்",
        "quantity": "அளவு (கிலோ)",
        "cost": "சாகுபடி செலவு (₹)",
        "days": "அறுவடை நாட்களுக்குப் பிறகு",
        "crop_image": "📸 பயிர் புகைப்படம்",
        "take_photo": "புகைப்படம் எடுக்கவும்",
        "analyze": "🚀 பகுப்பாய்வு செய்",
        "analyzing": "பகுப்பாய்வு செய்கிறது...",
        "error_req": "❌ பயிர் மற்றும் இடம் தேவை",
        "results": "📊 முடிவு",
        "price": "விலை",
        "freshness": "புத்துணர்ச்சி",
        "quality": "தரம்",
        "profit": "லாபம்",
        "recommendation": "பரிந்துரை",
        "captured": "பதிவு செய்யப்பட்டது",
        "cold_storage": "❄️ குளிர் சேமிப்பு பரிந்துரை",
        "cs_msg": "சேமிப்பது அதிக லாபம் தரும்! (+{profit_diff}%)",
        "nearest_cs": "அருகிலுள்ள குளிர் சேமிப்பு",
        "open_map": "வரைபடம் திற"
    },
    "kn": {
        "title": "🌾 AI ರೈತ ಸಲಹೆಗಾರ",
        "settings": "🌐 ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "lang_select": "ಭಾಷೆ",
        "farmer_details": "📝 ರೈತರ ವಿವರಗಳು",
        "crop_name": "ಬೆಳೆಯ ಹೆಸರು",
        "location": "ಗ್ರಾಮ / ನಗರ",
        "state": "ರಾಜ್ಯ",
        "quantity": "ಪ್ರಮಾಣ (ಕೆಜಿ)",
        "cost": "ಕೃಷಿ ವೆಚ್ಚ (₹)",
        "days": "ಕಟಾವು ಆಗಿ ಎಷ್ಟು ದಿನಗಳು",
        "crop_image": "📸 ಬೆಳೆಯ ಫೋಟೋ",
        "take_photo": "ಫೋಟೋ ತೆಗೆಯಿರಿ",
        "analyze": "🚀 ವಿಶ್ಲೇಷಿಸಿ",
        "analyzing": "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
        "error_req": "❌ ಬೆಳೆ ಮತ್ತು ಸ್ಥಳ ಅಗತ್ಯವಿದೆ",
        "results": "📊 ಫಲಿತಾಂಶ",
        "price": "ಬೆಲೆ",
        "freshness": "ತಾಜಾತನ",
        "quality": "ಗುಣಮಟ್ಟ",
        "profit": "ಲಾಭ",
        "recommendation": "ಶಿಫಾರಸು",
        "captured": "ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ",
        "cold_storage": "❄️ ಶೀತಲ ಸಂಗ್ರಹ ಸಲಹೆ",
        "cs_msg": "ಸಂಗ್ರಹಿಸುವುದು ಹೆಚ್ಚು ಲಾಭದಾಯಕ! (+{profit_diff}%)",
        "nearest_cs": "ಹತ್ತಿರದ ಶೀತಲ ಸಂಗ್ರಹ",
        "open_map": "ಮ್ಯಾಪ್ ತೆರೆಯಿರಿ"
    },
     "mr": {
        "title": "🌾 एआय शेतकरी सल्लागार",
        "settings": "🌐 सेटिंग्ज",
        "lang_select": "भाषा",
        "farmer_details": "📝 शेतकरी तपशील",
        "crop_name": "पिकाचे नाव",
        "location": "गाव / शहर",
        "state": "राज्य",
        "quantity": "प्रमाण (कि.ग्रा.)",
        "cost": "लागवड खर्च (₹)",
        "days": "काढणी नंतरचे दिवस",
        "crop_image": "📸 पिकाचा फोटो",
        "take_photo": "फोटो घ्या",
        "analyze": "🚀 विश्लेषण करा",
        "analyzing": "विश्लेषण करत आहे...",
        "error_req": "❌ पीक आणि ठिकाण आवश्यक आहे",
        "results": "📊 निष्कर्ष",
        "price": "भाव",
        "freshness": "ताजेपणा",
        "quality": "गुणवत्ता",
        "profit": "नफा",
        "recommendation": "शिफारस",
        "captured": "नोंदवले गेले",
        "cold_storage": "❄️ शीतगृह (Cold Storage) सल्ला",
        "cs_msg": "साठवण करणे अधिक फायदेशीर आहे! (+{profit_diff}%)",
        "nearest_cs": "जवळचे शीतगृह",
        "open_map": "नकाशा उघडा"
    }

}

def get_text(key, lang="en"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)
